apps/admin_panel/urls.py
from django.urls import path
from .import views 

urlpatterns = [
    path('login/', views.admin_login, name='admin_login'),
    path('logout/', views.admin_logout, name='admin_logout'),
    
    path('dashboard/', views.dashboard, name='dashboard'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  #media
from django.conf.urls.static import static #media


urlpatterns = [
    path('dj-admin/', admin.site.urls),
    path('admin/', include('apps.admin_panel.urls')),
    path('', include('apps.about_me.urls')),
    path('projects/', include('apps.portfolio.urls')),
    path('resume/', include('apps.resume.urls')),
    path('blogs/', include('apps.blogs.urls')),
    path('contact/', include('apps.contact.urls')),
    path('services/', include('apps.pricing.urls')), 
    path('users/', include('apps.users.urls')), 
    
] 


#for media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
    
    

apps/admin_panel/models.py
from django.db import models

# Create your models here.

apps/resume/models.py
from django.db import models

# Create your models here.
class BaseResume(models.Model):
    name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True
        
        
        
class Resume(BaseResume):
    position = models.CharField(max_length=50)
    mobile = models.CharField(max_length=20)
    email = models.EmailField()
    portfolio_url = models.URLField(max_length=20)
    address = models.CharField(max_length=100)
    image = models.ImageField()
    image_url = models.URLField(default='https://', blank=True, null=True)
    summary = models.TextField()
    
    linkedin_url = models.URLField(max_length=50, default='https://www.linkedin.com/in/amsbarik/')
    github_url = models.URLField(max_length=50, default='https://github.com/amsbarik')
    twitter_url = models.URLField(max_length=50, default='https://x.com/amsbarik')
    facebook_url = models.URLField(max_length=50, default='https://www.facebook.com/amsbarik')
    
    def __str__(self):
        return self.name
    
class ResumeExperience(BaseResume):
    resume = models.ForeignKey(Resume, related_name='resume_experience', on_delete=models.CASCADE)
    company = models.CharField(max_length=50)
    duration = models.CharField(max_length=50, default='year - year')
    role_desc = models.TextField()
    key_role_1 = models.CharField(max_length=100, blank=True, null=True)
    key_role_2 = models.CharField(max_length=100, blank=True, null=True)
    key_role_3 = models.CharField(max_length=100, blank=True, null=True)
    key_role_4 = models.CharField(max_length=100, blank=True, null=True)
    key_role_5 = models.CharField(max_length=100, blank=True, null=True)
    
    order = models.PositiveIntegerField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
class ResumeExperienceKey(BaseResume):
    resume_experience = models.ForeignKey(ResumeExperience, related_name='resume_experience_key', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
class ResumeProject(BaseResume):
    resume = models.ForeignKey(Resume, related_name='resume_project', on_delete=models.CASCADE)
    open_source_url = models.URLField(max_length=200, blank=True)
    project_live_url = models.URLField(max_length=200, blank=True)
    role_desc = models.TextField()
    
    technology_1 = models.CharField(max_length=50, blank=True, null=True)
    technology_2 = models.CharField(max_length=50, blank=True, null=True)
    technology_3 = models.CharField(max_length=50, blank=True, null=True)
    technology_4 = models.CharField(max_length=50, blank=True, null=True)
    technology_5 = models.CharField(max_length=50, blank=True, null=True)
    technology_6 = models.CharField(max_length=50, blank=True, null=True, default=None)
    technology_7 = models.CharField(max_length=50, blank=True, null=True, default=None)
    technology_8 = models.CharField(max_length=50, blank=True, null=True, default=None)
    technology_9 = models.CharField(max_length=50, blank=True, null=True, default=None)
    technology_10 = models.CharField(max_length=50, blank=True, null=True, default=None)
    
    order = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name
    
class ResumeProjectTechnology(BaseResume):
    resume_project = models.ForeignKey(ResumeProject, related_name='resume_project_technology', on_delete=models.CASCADE)
    order = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name
    
   
class TechnicalSkill(BaseResume):
    resume = models.ForeignKey(Resume, related_name='resume_technical_skill', on_delete=models.CASCADE)
    order = models.PositiveIntegerField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
class ProfessionalSkill(BaseResume):
    resume = models.ForeignKey(Resume, related_name='resume_professional_skill', on_delete=models.CASCADE)
    order = models.PositiveIntegerField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
class ResumeEducation(BaseResume):
    resume = models.ForeignKey(Resume, related_name='resume_education', on_delete=models.CASCADE)
    year = models.CharField(max_length=50, default='year - year')
    order = models.PositiveIntegerField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
class ResumeAward(BaseResume):
    resume = models.ForeignKey(Resume, related_name='resume_award', on_delete=models.CASCADE)
    year = models.CharField(max_length=50, default='year')
    order = models.PositiveIntegerField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
class ResumeLanguage(BaseResume):
    resume = models.ForeignKey(Resume, related_name='resume_language', on_delete=models.CASCADE)
    order = models.PositiveIntegerField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
class ResumeInterest(BaseResume):
    resume = models.ForeignKey(Resume, related_name='resume_interest', on_delete=models.CASCADE)
    order = models.PositiveIntegerField(null=True, blank=True)
    
    def __str__(self):
        return self.name

apps/users/models.py
from django.db import models
from datetime import datetime


# Create your models here.
class BaseUser(models.Model):
    name = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True


class Role(BaseUser):
    
    def __str__(self):
        return self.name
    
    
class Gender(BaseUser):
    
    def __str__(self):
        return self.name


class Team(BaseUser):
    member_id = models.CharField(max_length=10, unique=True, blank=True, null=True)
    profile_img = models.ImageField(null=True, blank=True, upload_to='developer_photo/')
    mobile = models.CharField(max_length=20)
    email = models.EmailField()
    nid = models.CharField(max_length=30)
    passport = models.CharField(max_length=30, null=True, blank=True)
    gender = models.ForeignKey(Gender, related_name='gender', on_delete=models.CASCADE)
    address = models.CharField(max_length=200)
    nationality = models.CharField(max_length=50, blank=True, null=True)
    religion = models.CharField(max_length=50, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    blood = models.CharField(max_length=6,blank=True, null=True)
    join_date = models.DateTimeField()
    rejoin_date = models.DateTimeField(blank=True, null=True)
    role = models.ForeignKey(Role, related_name='employee_role', on_delete=models.CASCADE)
    skill = models.TextField()
    
    resume = models.FileField(upload_to='developer_resume/', default='resume.pdf')
    portfolio_url = models.URLField(max_length=200, blank=True,  default='https://www.yourdomain.com')
    github_url = models.URLField(max_length=200, blank=True,  default='https://www.github.com/')
    linkedin_url = models.URLField(max_length=200, blank=True,  default='https://www.linkedin.com/')
    stackoverflow_url = models.URLField(max_length=200, blank=True,  default='https://www.stackoverflow.com/')
    reddit_url = models.URLField(max_length=200, blank=True,  default='https://www.reddit.com/')
    facebook_url = models.URLField(max_length=200, blank=True, default='https://www.facebook.com/')
    
    intro = models.TextField(blank=True, null=True, default='I am ')
    
    order = models.PositiveIntegerField(null=True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.member_id:
            last_member = Team.objects.all().order_by('id').last()
            if last_member:
                last_id = int(last_member.member_id.replace('DEV', ''))
                new_id = last_id + 1
            else:
                new_id = 4101
            self.member_id = f'DEV{new_id}'
        super(Team, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name
    





# user settings model
class UserSetting(BaseUser):
    
    user_photo = models.ImageField(upload_to='users/', blank=True, default='users/user-photo.jpg')
    position = models.CharField(max_length=50, blank=True)
    intro = models.TextField(blank=True)
    mobile = models.CharField(max_length=20, blank=True)
    email = models.EmailField(blank=True)
    location = models.CharField(max_length=100, blank=True)
    
    website_url = models.URLField(default='https://', blank=True)
    linkedin_url = models.URLField(default='https://', blank=True)
    github_url = models.URLField(default='https://', blank=True)
    stackoverflow_url = models.URLField(default='https://', blank=True)
    twitter_url = models.URLField(default='https://', blank=True)
    reddit_url = models.URLField(default='https://', blank=True)
    facebook_url = models.URLField(default='https://', blank=True)
    
    logo = models.ImageField(upload_to='users/', blank=True, default='users/logo.jpg')
    fav_icon = models.ImageField(upload_to='users/', blank=True, default='users/fav-icon.png')
    index_title = models.CharField(max_length=254, blank=True)
    index_meta_kewords = models.TextField(blank=True)
    short_desc = models.TextField(blank=True)
    
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Site Settings"
    
    
    
    
    
    

apps/admin_panel/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

# admin login form
class CustomAdminLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
        label=''  # Hide label
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
        label=''  # Hide label
    )

apps/admin_panel/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import user_passes_test, login_required
from .forms import CustomAdminLoginForm

from apps.users.views import is_superuser


# Create your views here.

# admin login 
def admin_login(request):
    if request.method == 'POST':
        form = CustomAdminLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None and user.is_superuser:
                login(request, user)
                return redirect('dashboard')
                # return redirect('admin:index') #this django admin panel
    else:
        form = CustomAdminLoginForm()
    return render(request, 'admin_panel/admin_login.html', {'form': form})


# logout 
@login_required
@user_passes_test(lambda u: u.is_superuser)
def admin_logout(request):
    logout(request)
    return redirect('index') 


# admin dashboard view
@login_required
@user_passes_test(is_superuser)
def dashboard(request):
    return render(request, 'admin_panel/dashboard.html')

apps/admin_panel/templates/admin_panel/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>Portal - Bootstrap 5 Admin Dashboard Template For Developers</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="favicon.ico"> 
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'assets/plugins/fontawesome/js/all.min.js' %}"></script>
    <!-- font awesome link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- bootstrap cdn link  -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->

    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/apps.css' %}">

    <!-- root css  -->
    <style>
        :root{
            --primary : #27b674;
            --primary-deep : #21a768;
            --secondary: #AED2ED;
            --dark: #26362E;
            --dark-deep: #24302a;
            --warning: #F4E87B;
            --info: #E698F2;
            --danger: #E84736;
            --danger-deep: #da4433;
            --white: #ffffff;
            --light: #fafafa;
        }
     </style>

    <!-- reset css  -->
     <style>
        .form-select:focus{
            outline: none;
            box-shadow: none;
            border: 1px solid #27b674;
        }
        .form-control:focus{
            border: 1px solid #27b674;
        }
        .form-label:hover{
            cursor: pointer;
        }

        .form .form-control, .form .form-select{
            margin-top: -1.1rem;
            padding-top: .8rem;
            font-size: 0.875rem;
            background: #ffffff;
        }
        .form .form-label{
            margin-left: .65rem;
            background: #ffffff;
            padding: 0 .3rem;
            font-size: 0.875rem;
            text-transform: capitalize;
        }

        

        /* btn class  */
        .btn{
            /* color: var(--white); */
            font-weight: 600;
            padding: .4rem 1.5rem;
            /* border: none; */
        }
        .btn-primary{
            color: var(--white);
            background: var(--primary);
        }
        .btn-primary:hover{
            color: var(--white);
            background: var(--primary-deep);
        }
        .btn-dark{
            background: var(--dark);
            color: var(--white);
        }
        .btn-dark:hover{
            color: var(--white);
            background: var(--dark-deep);
        }
        .btn-danger{
            background: var(--danger);
            color: var(--white);
        }
        .btn-danger:hover{
            color: var(--white);
            background: var(--danger-deep);
        }


        /* in form  */
        #id_summary, #id_role_desc, #id_intro, #id_comments{
            height: 200px;
        }

        /* testimonial form css start */
        #id_testimonial_type {
            display: flex;
            margin-bottom: .7rem;
        }
        #id_testimonial_type div {
            margin-right: 1rem;
            font-weight: 500;
            font-size: 1.1rem;
        }
        #id_testimonial_type_0, #id_testimonial_type_1{
            accent-color: #23a167;
        }
     </style>



</head> 
<!-- password username -->
<body class="app app-login p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4">
                        {% if logo %}
                        <a class="app-logo" href="{% url 'index' %}"><img class="logo-icon me-2 rounded-circle" src="{{ logo }}" alt="logo"></a>
                        {% endif %}
                    </div>
					<h2 class="auth-heading text-center mb-5">Admin Login</h2>
			        <div class="auth-form-container text-start">
					    <!-- <form class="auth-form login-form">         
							<div class="email mb-3">
								<label class="sr-only" for="signin-email">Email</label>
								<input id="signin-email" name="username" type="text" class="form-control signin-email" placeholder="Email address" required="required">
							</div>

							<div class="password mb-3">
								<label class="sr-only" for="signin-password">Password</label>
								<input id="signin-password" name="password" type="password" class="form-control signin-password" placeholder="Password" required="required">
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										<div class="form-check">
											<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
											<label class="form-check-label" for="RememberPassword">
											Remember me
											</label>
										</div>
									</div>
                                    
									<div class="col-6">
										<div class="forgot-password text-end">
											<a href="reset-password.html">Forgot password?</a>
										</div>
									</div>

								</div>
							</div>

							<div class="text-center">
								<button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto">Log In</button>
							</div>

						</form>  -->

                        <form method="post" class="auth-form login-form">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <div class="extra mt-3 row justify-content-between">
                                <div class="col-6">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="" id="RememberPassword">
                                        <label class="form-check-label" for="RememberPassword"> Remember me</label>
                                    </div>
                                </div>
                                
                                <div class="col-6">
                                    <div class="forgot-password text-end">
                                        <a href="#">Forgot password?</a>
                                    </div>
                                </div>

                            </div>

                            <button type="submit" class="btn btn-primary mt-4" style="width: 100%;">Login</button>
                        </form>
						
						<div class="auth-option text-center pt-5">No Account? Sign up <a class="text-link" href="#" >here</a>.</div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
			        <small class="copyright">Developed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="https://barik.me" target="_blank">barik.me</a> for me</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				    <!-- <div class="overlay-content p-3 p-lg-4 rounded">
					    <h5 class="mb-3 overlay-title">Explore Portal Admin Template</h5>
					    <div>Portal is a free Bootstrap 5 admin dashboard template. You can download and view the template license <a href="https://themes.3rdwavemedia.com/bootstrap-templates/admin-dashboard/portal-free-bootstrap-admin-dashboard-template-for-developers/">here</a>.</div>
				    </div> -->
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->




    <!-- Javascript bootstrap downloaded offline -->          
    <script src="{% static 'assets/plugins/popper.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>  
    
    <!-- Page Specific JS -->
    <script src="{% static 'assets/js/app.js' %}"></script> 


</body>
</html> 

apps/admin_panel/templates/admin_panel/drafts.html
{% extends 'admin_panel/layouts/master.html' %}
{% block title %} Messages {% endblock title %}

{% block content %}

<h1 class="app-page-title">Overview</h1>
			    
			    


{% endblock content %}